;;;; mincss.import.scm - GENERATED BY CHICKEN 4.11.0 -*- Scheme -*-

(eval '(import chicken scheme ports srfi-1 sxml-transforms sxpath-lolevel))
(##sys#register-compiled-module
  'mincss
  (list)
  '((mincss-rules . mincss#mincss-rules)
    (sxml->html . mincss#sxml->html)
    (mincss-cdn-url . mincss#mincss-cdn-url))
  (list)
  (list))

;; END OF FILE
